services:
  subscription:
    build: .
    ports:
      - "50055:50055"
    env_file:
      - ./cmd/.env
    volumes:
      - ./logs:/app/logs
    networks:
      - subscription-network
    depends_on:
      - media
      - review
      - watchlist
      - user

  media:
    image: media-media
    ports:
      - "50051:50051"
    networks:
      - subscription-network

  user:
    image: user-user
    ports:
      - "50052:50052"
    networks:
      - subscription-network

  review:
    image: review-review
    ports:
      - "50053:50053"
    networks:
      - subscription-network

  watchlist:
    image: watchlist-watchlist
    ports:
      - "50054:50054"
    networks:
      - subscription-network

networks:
  subscription-network:
    driver: bridge
